### ISSUE TITLE
تغيير رابط التويتر

### ISSUE THREAD

**Issue by seddik** [seddik/fikratech-site#1]

**Comment by bmayoub** [comment]
ما لقيتش رابط تع تويتر وما لقيتش يوتيوب وما لقيت والو، غيرهم أنت

**Comment by bmayoub** [comment]
ولا ابعثلي الروابط الصحيحة وانا نغيرها

**Comment by seddik** [comment]
https://twitter.com/fikratech
https://www.youtube.com/channel/UCtCx81bM-1nQ0T-jjJXpxcw

**Comment by bmayoub** [comment]
وصفحة الفيسبوك؟

**Comment by seddik** [comment]
الصفحة نحولو clubtic lel fikratech

**Comment by bmayoub** [comment]
هذيك مجموعة
أنا نحوس على صفحة كاينة ولا نستعملوا هذيك اللي فتحتها انا وفيها 196 معجب 
https://www.facebook.com/clubtictggt

**Comment by seddik** [comment]
لالا هاذي وممكن المجموعة نحوها كامل نحول الناس لهاذي
