### ISSUE TITLE
مواقع التواصل الإجتماعي إضافة أكثر عدد ممكن من المواقع

### ISSUE THREAD

**Issue by seddik** [seddik/fikratech-site#10]

**Comment by seddik** [comment]
- إنستجرام
- جت هب للمشاريع المتبنات
- وحتى رابط المنتدى إذا تمت الموافقة

**Comment by bmayoub** [comment]
في رايي ما تفتحش انستغرام حتى تتأكد أن هناك من سيقوم عليه
موقع او موقعين تواصل اجتماعي فاعلين خير من 10 مواقع وغير فعالة

**Comment by bmayoub** [comment]
بالنسبة لجيت هب أنت رح تشرف على المشاريع فافتح أنت حساب وابعثلي الرابط
وبالنسبة للمنتدى رانا نستنو في الجماعة يردو ومكان والو

**Comment by seddik** [comment]
أنستجرام مهم ياسر لأننا ناقصين صور ياسر، فبعد كل ندوة أو إجتماع نوضغو فيه صور، سيكون بمثاة بنك للصور نتاع الجمعية
