### ISSUE TITLE
إستخام الجزيرة لايت 600 لأنه أحسن وأوضح وأجمل بكثير من 300

### ISSUE THREAD

**Issue by seddik** [seddik/fikratech-site#11]
![image](https://user-images.githubusercontent.com/6674347/30379485-8bb078d6-988e-11e7-8379-9b0daa3ca96d.png)

**Comment by bmayoub** [comment]
تم
 شوف الآن

**Comment by seddik** [comment]
![image](https://user-images.githubusercontent.com/6674347/30400981-91ee64e6-98d0-11e7-8ec5-8bd8abeebd76.png)

![image](https://user-images.githubusercontent.com/6674347/30400993-9d419e94-98d0-11e7-9401-2b25fc0a0416.png)

**Comment by bmayoub** [comment]
تم
شوف الآن

**Comment by seddik** [comment]
والو يبات متقطع والحروف متلاصقة، حاليا نخلوه هكذا مبعد نديرولو راي
