### ISSUE TITLE
إضافة فرق العمل

### ISSUE THREAD

**Issue by bmayoub** [seddik/fikratech-site#16]
هناك إضافة لعرض فرق عمل أو لجان
لا أعرف هل هي ضرورية أم لا وفيم يمكن استخدامها
ما رأيكم بها؟
https://themepoints.com/teamshowcase/

**Comment by seddik** [comment]
ممكن نضيفوها لكن كصفحة خاصة وفي الصفحة الرئيسية نحطو الأعضاء الجدد فقط، هكذا باش ما أي واح يعرف بنفسو وباش ما نحسسوش الناس بلي الجمعية نتاع فلان وهاهم الناس لي شادينها، وإنما جميع الناس المشاركين ممكن تتحط أسمائهم ويقدكمو أنفسهم

**Comment by bmayoub** [comment]
أنا قلت في كل لجنة يتم اعتمادها نحطو صور أعضاءها
ونديرو صفحة لمكتب الجمعية
ونديرو للمحاضرين أيضا
