### ISSUE TITLE
إختيار خط وتطبيقه على كامل الموقع

### ISSUE THREAD

**Issue by seddik** [seddik/fikratech-site#2]

**Comment by bmayoub** [comment]
أي خط يكون مليح، أنا برك حبيت ننبه إلى فكرة
ليست لدينا مقالات طويلة كل أخبارنا قصيرة ، لذلك يجب أن يكون الخط ذو حجم كبير والتعليقات أيضا يجب أن تكون بحجم خط كبير، نكره المواقع اللي التعليقات فيها صغيرة الحجم مثل يوتيوب

**Comment by seddik** [comment]
واش رايك في خط المدونة نتاعي
http://blog.optimdz.com

**Comment by bmayoub** [comment]
مليح بصح يمكن نلقوا أحسن منه، جربته فلات من قبل وناس تعاني من قراءته

**Comment by seddik** [comment]
لكن أضرب حسابك الخط هو الواجهة نتاع الموقع، كون نخطو الخطوط العادية يعود الموقع يبان مفرطح 😆

**Comment by bmayoub** [comment]
أكيد، يعجبني خط الجزيرة بزاف أنا

**Comment by bmayoub** [comment]
يا جماعة ادخلوا في النقاش واعطونا رايكم
هاهي قائمة بالخطوط
https://fontface.me/font/list

**Comment by seddik** [comment]
خط الجزيرة ما عجبنيش

**Comment by GeekAbdelouahed** [comment]
كاين المجموعة هذي موالف نختار منها 
https://www.template.net/design-templates/fonts/calligraphy-arabic-fonts/

**Comment by GeekAbdelouahed** [comment]
عني هذي الخطوط في الجهاز أيضا
![best-76-free-arabic-font-preview-1](https://user-images.githubusercontent.com/22131872/30325658-78ce1038-97bd-11e7-8e45-7b3f6b390ef1.jpg)

**Comment by GeekAbdelouahed** [comment]
![best-76-free-arabic-font-preview-2](https://user-images.githubusercontent.com/22131872/30325730-bb5edd9c-97bd-11e7-8a1d-776594fa0d75.jpg)

**Comment by bmayoub** [comment]
خط أسامة يبان مليح ولا لا؟ رقم 28

**Comment by seddik** [comment]
المهم الخط ما يكونش غليظ لأنو يقلق ويبشع الموقع كيما الخطين الأخيرين في الموقع، العناوين غليظة والمحتوى غليظ كذلك

**Comment by GeekAbdelouahed** [comment]
ملف الخطوط كاملة

[+50 Free Arabic Font.zip](https://github.com/mslaraba/fikratech-site/files/1296671/50.Free.Arabic.Font.zip)
