### ISSUE TITLE
عدم ظهور خريطة عند اضافة حدث

### ISSUE THREAD

**Issue by bmayoub** [seddik/fikratech-site#3]
عند إضافة event
ومحاولة تحديد الموقع على خريطة جوجل فإن خريطة جوجل لا تظهر ولا اعرف لماذا

**Comment by bmayoub** [comment]
عفوًا، حدث خطأ ما.
‏لم تحمِّل هذه الصفحة خرائط Google بشكل صحيح. راجع وحدة تحكم جافا سكريبت للاطلاع على التفاصيل التقنية.

**Comment by seddik** [comment]
هل دخلت مفتاح قوقل ماب API_KEY ??!!

**Comment by bmayoub** [comment]
كاين زوج اضافات خاصين بالخرائط،
الاضافة اللي تجي مع القالب دخلتلها آبي كاي
الاضافة هذه ما لقيتش وين ندخل آبي كاي
الإعدادات > google maps

**Comment by seddik** [comment]
https://wordpress.org/plugins/google-maps-easy/ 
هاذ الإضافة مليحة ومريقلة

**Comment by bmayoub** [comment]
ما فهمتنيش، هذه اضافة الأحداث 
event+
لما تحب تضيف مكان الحدث تستعمل الاضافة تاعهم
wpmu google maps
ما تقدرش تستعمل اضافة اخرى غيرها
لما تكون متفرغ أدخل للموقع واخرب
