### ISSUE TITLE
إستحداث منتدى

### ISSUE THREAD

**Issue by bmayoub** [seddik/fikratech-site#4]
نناقش ضرورة وجود منتدى
أنا نشوف فيه ضروري لأن النقاشات في مجموعة الفيسبوك محدودة جدا والفيسبوك ليس مهيئ لهذا النوع من النقاشات
والمنتدى احسن في الارشفة وتبيين الاعضاء الفاعلين من خلال عدد المشاركات والأوسمة والرتب
كذلك أنوي جعل منتدى لكل لجنة عمل حتى نساعد أعضاء اللجنة على الحوار عبر الانترنت في حال تعذر الحضور
كذلك يجب سحب الناس من الفيسبوك لأنه مصدر إلهاء أكثر منه مصدر معرفة

**Comment by seddik** [comment]
هل المنتدى هذاك يدعم العربية بشكل جيد ??!!

**Comment by bmayoub** [comment]
نعم جيد جدا، اصبر نحوسلك على مثال

**Comment by bmayoub** [comment]
الموقع اللي كنت نعرفه يستخدمو شكله أغلق
https://meraj.team/
بصح كان هايل تع الصح
وما تقلقكش التعريب راني نصحح اذا لقيت اختلالات في الشكل أو النص

**Comment by seddik** [comment]
لا قصدي اليمين إلى اليسار والأشياء الخاصة بالعربية

**Comment by bmayoub** [comment]
ايه يدعمها مليح، أنا كنت ناشط في المنتدى تاعهم بصح شكلهم حبسو 
كان اسمه فريق معراج

**Comment by seddik** [comment]
أنا راني معاك لكن نشوفو الآراء نتاع الشبيبة وممكن نوجدو قائمة محاسن ومساويء هكذا باش نكونو متأكدين

**Comment by bmayoub** [comment]
استدعيهم يتحاورو معانا هنا، يمكن عندهم افكار للموقع ايضا وأعطيهم رابط الموقع

**Comment by bmayoub** [comment]
أين هو المنتدى، قم بتثبيته حتى نقوم بضبط إعداداته

**Comment by seddik** [comment]
كيف نثبتو ??!! يخي هذاك الموقع يعطيك الإستضافة أو نحطو إستضافة من عندنا على شكل
forum.fikra.ml

**Comment by seddik** [comment]
إذا كان لازم إستضافتنا من فضلك أعطيني رابط الموقع لي يعطيك فوروم

**Comment by bmayoub** [comment]
يعطيك استضافة بالدراهم 100 دولار للشهر، 
متقدرش تصطاليه في استضافتنا مباشرة مثل بقية المنتديات؟؟

**Comment by bmayoub** [comment]
كارثة
هذا وين عرفت أن المنتدى ما تقدرش تثبته في استضافة مشتركة
تطياح المورال

**Comment by seddik** [comment]
علاه يا سيدي نعطوكم إستضافة خاصة أي حاجة تحب تثبتها نثبتوها

**Comment by seddik** [comment]
أبعثلي الرابط نتاعو

**Comment by bmayoub** [comment]
https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

**Comment by bmayoub** [comment]
راني ركبت اضافة منتدى أخرى 
bbpress
بسيط فوق اللازم، مع شوية خدمة بـ css نخلوه مليح
