### ISSUE TITLE
حساب تويتر

### ISSUE THREAD

**Issue by bmayoub** [seddik/fikratech-site#5]
نحتاج ندخل لحساب تويتر تع الجمعية باه نخلي آخر التغريدات تظهر في الموقع
ابعثولي المعلومات على الخاص

**Comment by bmayoub** [comment]
وصلتني تم

**Comment by seddik** [comment]
ما تنساش بأن هنا كل مفتوح المصدر يعني الناس كلها تشوف، ما نقدرش نرسلك كلمة المرور

**Comment by seddik** [comment]
وكي يكمل المشكل ISSUE لازم تدير CLOSE

**Comment by seddik** [comment]
![image](https://user-images.githubusercontent.com/6674347/30292870-95a77ffc-972f-11e7-9ced-38f553ddd90a.png)

**Comment by bmayoub** [comment]
أنا كنت ندير lock نحسب روحي غلقت المشكل

**Comment by bmayoub** [comment]
راني ما قدرتش ندخل للحساب

**Comment by seddik** [comment]
عاود أفتح واحد جديد وخلاص، جماعة الإعلام خربطو الحالة أنا فتحتلهم كونت وواحد دخل وحب يبدل المودباس والله ما فهمت، رجعتهولو وعاود راح
